use designweardb;
show tables;
INSERT INTO `professor` (`idprofessor`, `nome`, `login`, `senha`, `email`) VALUES (NULL, 'Valdir', 'LoginProfTeste', '1234', 'testeprof@email.com');
INSERT INTO `aluno` (`matricula`, `login`, `senha`, `nome`, `pctcursoconcluido`, `idprofessor`) VALUES ('1234', 'alunologin', '4321', 'Teste da Silva', '15', '1');
INSERT INTO atividade(titulo, descricao)VALUES('Atividade 1', '1ª atividade');
SET @id_atividade = LAST_INSERT_ID();
INSERT INTO atividade(titulo, descricao)VALUES('Atividade 2', '2ª atividade');
SET @id_atividade = LAST_INSERT_ID();
INSERT INTO atividade(titulo, descricao)VALUES('Atividade 3', '3ª atividade');
SET @id_atividade = LAST_INSERT_ID();
INSERT INTO atividade(titulo, descricao)VALUES('Atividade 4', '4ª atividade');
SET @id_atividade = LAST_INSERT_ID();
INSERT INTO atividade(titulo, descricao)VALUES('Atividade 5', '5ª atividade');
SET @id_atividade = LAST_INSERT_ID();
INSERT INTO nota(matricula, id_atividade, nota, idprofessor)VALUES('1234', '1', '6.5', '1');
INSERT INTO nota(matricula, id_atividade, nota, idprofessor)VALUES('1234', '2', '7.5', '1');
INSERT INTO nota(matricula, id_atividade, nota, idprofessor)VALUES('1234', '3', '9.5', '1');
INSERT INTO nota(matricula, id_atividade, nota, idprofessor)VALUES('1234', '4', '2.5', '1');
INSERT INTO nota(matricula, id_atividade, nota, idprofessor)VALUES('1234', '5', '1.5', '1');
select * from professor;
select * from aluno;
select * from atividade;
select * from nota;